version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/skadoosh:latest
    working_directory: /home/alpine/circle/
    steps:
      - run:
          name: Initialize
          command: |
            git clone --bare https://github.com/EnergizedProtection/mirror
            cd mirr*
            git push -f --mirror https://$GitHubName:$GITHUB_TOKEN@github.com/EnergizedPro/mirror.git
workflows:
  version: 2
  energied:
    jobs:
      - build:
          context: org-global
