version: 2.1
jobs:
  build:
    docker:
      - image: fr3akyphantom/skadoosh:latest
    working_directory: /home/alpine/circle/
    steps:
      - run:
          name: Initialize
          command: |
            curl -sL https://github.com/EnergizedProtection/block/archive/master.zip -o EnergizedProtection_block.zip
            7z x EnergizedProtection_block.zip && rm EnergizedProtection_block.zip
            cd block-master
            du -sh .
            git init
            curl -sL https://gist.github.com/rokibhasansagar/89dd796f9c69d6d2402d1205873393d7/raw/commit-msg -o .git/hooks/commit-msg && chmod a+x .git/hooks/commit-msg
            git add -A .
            git remote add origin https://$GitHubName:$GITHUB_TOKEN@github.com/EnergizedPro/block.git
            git commit -s -m "Blank Slate"
            git push -f origin master
workflows:
  version: 2
  energied:
    jobs:
      - build:
          context: org-global
